dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist

script: ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly
  include:
    - stage: Psalm
      php: 7.4
      script:
        - ./vendor/bin/psalm

    - stage: Code Style
      php: 7.4
      script:
        - ./vendor/bin/phpcs