dist: trusty
sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer self-update

jobs:
  include:
    - stage: Psalm
      php: 7.4
      install: travis_retry composer install --prefer-dist
      script:
        - vendor/bin/psalm

    - stage: Test
      install: travis_retry composer install --prefer-dist
      script:
        - ./vendor/bin/phpunit

    - stage: Code Style
      php: 7.4
      install: travis_retry composer install --prefer-dist
      script:
        - vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache
